<div class="front">
	<div class="layer">
		<div class="close closeme" title="Esc">×</div>
		<div class="gtitle">Informacion sobre la Comunidad</div>
		<div class="row">
			<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
				<div class="panel panel-success" style="margin-top:2%;">
					<div class="panel-body">
						<p dir="ltr" style="line-height:1.15;margin-top:20pt;margin-bottom:0pt;">
			<span id="docs-internal-guid-0bc2142d-bc9b-1e64-a071-c15c014c9fe2"><span style="font-size: 15px; font-family: Arial; font-weight: bold; text-decoration: underline; vertical-align: baseline; white-space: pre-wrap;">Informaci&oacute;n de la Educaci&oacute;n</span></span></p>
		<p dir="ltr" style="line-height:1.15;margin-top:20pt;margin-bottom:0pt;">
			<span id="docs-internal-guid-0bc2142d-bc9b-1e64-a071-c15c014c9fe2"><span style="font-size: 15px; font-family: Arial; font-weight: bold; vertical-align: baseline; white-space: pre-wrap;">Escuelas p&uacute;blicas</span></span></p>
		<p dir="ltr" style="line-height:1.15;margin-top:20pt;margin-bottom:0pt;">
			<span id="docs-internal-guid-0bc2142d-bc9b-1e64-a071-c15c014c9fe2"><span style="font-size: 15px; font-family: Arial; vertical-align: baseline; white-space: pre-wrap;">Distrito Escolar Independiente de Conroe ( </span><a href="http://www.conroeisd.net/" style="text-decoration:none;"><span style="font-size: 15px; font-family: Arial; color: rgb(17, 85, 204); text-decoration: underline; vertical-align: baseline; white-space: pre-wrap;">http://www.conroeisd.net/</span></a><span style="font-size: 15px; font-family: Arial; vertical-align: baseline; white-space: pre-wrap;"> )</span></span></p>
		<p dir="ltr" style="line-height:1.15;margin-top:20pt;margin-bottom:0pt;">
			<span id="docs-internal-guid-0bc2142d-bc9b-1e64-a071-c15c014c9fe2"><span style="font-size: 15px; font-family: Arial; vertical-align: baseline; white-space: pre-wrap;">Distrito Escolar Independiente de Klein ( </span><a href="http://www.kleinisd.net/" style="text-decoration:none;"><span style="font-size: 15px; font-family: Arial; color: rgb(17, 85, 204); text-decoration: underline; vertical-align: baseline; white-space: pre-wrap;">http://www.kleinisd.net/</span></a><span style="font-size: 15px; font-family: Arial; vertical-align: baseline; white-space: pre-wrap;"> )</span></span></p>
		<p dir="ltr" style="line-height:1.15;margin-top:20pt;margin-bottom:0pt;">
			<span id="docs-internal-guid-0bc2142d-bc9b-1e64-a071-c15c014c9fe2"><span style="font-size: 15px; font-family: Arial; vertical-align: baseline; white-space: pre-wrap;">Distrito Escolar Independiente de Tomball ( </span><a href="http://www.tomballisd.net/" style="text-decoration:none;"><span style="font-size: 15px; font-family: Arial; color: rgb(17, 85, 204); text-decoration: underline; vertical-align: baseline; white-space: pre-wrap;">http://www.tomballisd.net/</span></a><span style="font-size: 15px; font-family: Arial; vertical-align: baseline; white-space: pre-wrap;"> )</span></span></p>
		<p dir="ltr" style="line-height:1.15;margin-top:20pt;margin-bottom:0pt;">
			<span id="docs-internal-guid-0bc2142d-bc9b-1e64-a071-c15c014c9fe2"><span style="font-size: 15px; font-family: Arial; vertical-align: baseline; white-space: pre-wrap;">Distrito Escolar Independiente de Magnolia ( </span><a href="http://www.magnoliaisd.org/education/district/district.php?sectionid=1" style="text-decoration:none;"><span style="font-size: 15px; font-family: Arial; color: rgb(17, 85, 204); text-decoration: underline; vertical-align: baseline; white-space: pre-wrap;">http://www.magnoliaisd.org/education/district/district.php?sectionid=1</span></a><span style="font-size: 15px; font-family: Arial; vertical-align: baseline; white-space: pre-wrap;"> )</span></span></p>
		<p dir="ltr" style="line-height:1.15;margin-top:20pt;margin-bottom:0pt;">
			<span id="docs-internal-guid-0bc2142d-bc9b-1e64-a071-c15c014c9fe2"><span style="font-size: 15px; font-family: Arial; vertical-align: baseline; white-space: pre-wrap;">Distrito Escolar Independiente de Houston ( </span><a href="http://www.houstonisd.org/site/default.aspx?PageID=1" style="text-decoration:none;"><span style="font-size: 15px; font-family: Arial; color: rgb(17, 85, 204); text-decoration: underline; vertical-align: baseline; white-space: pre-wrap;">http://www.houstonisd.org/site/default.aspx?PageID=1</span></a><span style="font-size: 15px; font-family: Arial; vertical-align: baseline; white-space: pre-wrap;"> )</span></span></p>
		<p dir="ltr" style="line-height:1.15;margin-top:20pt;margin-bottom:0pt;">
			<span id="docs-internal-guid-0bc2142d-bc9b-1e64-a071-c15c014c9fe2"><span style="font-size: 15px; font-family: Arial; vertical-align: baseline; white-space: pre-wrap;">Humble Independent School District ( </span><a href="http://www.humble.k12.tx.us/site/default.aspx?PageID=1" style="text-decoration:none;"><span style="font-size: 15px; font-family: Arial; color: rgb(17, 85, 204); text-decoration: underline; vertical-align: baseline; white-space: pre-wrap;">http://www.humble.k12.tx.us/site/default.aspx?PageID=1</span></a><span style="font-size: 15px; font-family: Arial; vertical-align: baseline; white-space: pre-wrap;"> )</span></span></p>
		<p dir="ltr" style="line-height:1.15;margin-top:20pt;margin-bottom:0pt;">
			<span id="docs-internal-guid-0bc2142d-bc9b-1e64-a071-c15c014c9fe2"><span style="font-size: 15px; font-family: Arial; vertical-align: baseline; white-space: pre-wrap;">Distrito Escolar Independiente de Montgomery ( </span><a href="http://www.misd.org/" style="text-decoration:none;"><span style="font-size: 15px; font-family: Arial; color: rgb(17, 85, 204); text-decoration: underline; vertical-align: baseline; white-space: pre-wrap;">http://www.misd.org/</span></a><span style="font-size: 15px; font-family: Arial; vertical-align: baseline; white-space: pre-wrap;"> )</span></span></p>
		<p dir="ltr" style="line-height:1.15;margin-top:20pt;margin-bottom:0pt;">
			<span id="docs-internal-guid-0bc2142d-bc9b-1e64-a071-c15c014c9fe2"><span style="font-size: 15px; font-family: Arial; font-weight: bold; vertical-align: baseline; white-space: pre-wrap;">Escuelas privadas</span></span></p>
		<p dir="ltr" style="line-height:1.15;margin-top:20pt;margin-bottom:0pt;">
			<span id="docs-internal-guid-0bc2142d-bc9b-1e64-a071-c15c014c9fe2"><span style="font-size: 15px; font-family: Arial; vertical-align: baseline; white-space: pre-wrap;">La Escuela John Cooper ( </span><a href="https://www.johncooper.org/" style="text-decoration:none;"><span style="font-size: 15px; font-family: Arial; color: rgb(17, 85, 204); text-decoration: underline; vertical-align: baseline; white-space: pre-wrap;">https://www.johncooper.org/</span></a><span style="font-size: 15px; font-family: Arial; vertical-align: baseline; white-space: pre-wrap;"> )</span></span></p>
		<p dir="ltr" style="line-height:1.15;margin-top:20pt;margin-bottom:0pt;">
			<span id="docs-internal-guid-0bc2142d-bc9b-1e64-a071-c15c014c9fe2"><span style="font-size: 15px; font-family: Arial; vertical-align: baseline; white-space: pre-wrap;">La Academia Cristiana Woodlands ( </span><a href="http://www.twca.net/" style="text-decoration:none;"><span style="font-size: 15px; font-family: Arial; color: rgb(17, 85, 204); text-decoration: underline; vertical-align: baseline; white-space: pre-wrap;">http://www.twca.net/</span></a><span style="font-size: 15px; font-family: Arial; vertical-align: baseline; white-space: pre-wrap;"> )</span></span></p>
		<p dir="ltr" style="line-height:1.15;margin-top:20pt;margin-bottom:0pt;">
			<span id="docs-internal-guid-0bc2142d-bc9b-1e64-a071-c15c014c9fe2"><span style="font-size: 15px; font-family: Arial; vertical-align: baseline; white-space: pre-wrap;">San Antonio de Padua Escuela Cat&oacute;lica ( </span><a href="http://www.staopcs.org/" style="text-decoration:none;"><span style="font-size: 15px; font-family: Arial; color: rgb(17, 85, 204); text-decoration: underline; vertical-align: baseline; white-space: pre-wrap;">http://www.staopcs.org/</span></a><span style="font-size: 15px; font-family: Arial; vertical-align: baseline; white-space: pre-wrap;"> )</span></span></p>
		<p dir="ltr" style="line-height:1.15;margin-top:20pt;margin-bottom:0pt;">
			<span id="docs-internal-guid-0bc2142d-bc9b-1e64-a071-c15c014c9fe2"><span style="font-size: 15px; font-family: Arial; vertical-align: baseline; white-space: pre-wrap;">Esprit International School ( </span><a href="http://www.espritinternationalschool.com/" style="text-decoration:none;"><span style="font-size: 15px; font-family: Arial; color: rgb(17, 85, 204); text-decoration: underline; vertical-align: baseline; white-space: pre-wrap;">http://www.espritinternationalschool.com/</span></a><span style="font-size: 15px; font-family: Arial; vertical-align: baseline; white-space: pre-wrap;"> )</span></span></p>
		<p dir="ltr" style="line-height:1.15;margin-top:20pt;margin-bottom:0pt;">
			<span id="docs-internal-guid-0bc2142d-bc9b-1e64-a071-c15c014c9fe2"><span style="font-size: 15px; font-family: Arial; vertical-align: baseline; white-space: pre-wrap;">Cunae International School ( </span><a href="http://www.doortomyschool.com/" style="text-decoration:none;"><span style="font-size: 15px; font-family: Arial; color: rgb(17, 85, 204); text-decoration: underline; vertical-align: baseline; white-space: pre-wrap;">http://www.doortomyschool.com/</span></a><span style="font-size: 15px; font-family: Arial; vertical-align: baseline; white-space: pre-wrap;"> )</span></span></p>
		<p dir="ltr" style="line-height:1.15;margin-top:20pt;margin-bottom:0pt;">
			<span id="docs-internal-guid-0bc2142d-bc9b-1e64-a071-c15c014c9fe2"><span style="font-size: 15px; font-family: Arial; vertical-align: baseline; white-space: pre-wrap;">La Escuela Preparatoria Woodlands ( </span><a href="http://www.woodlandsprep.org/" style="text-decoration:none;"><span style="font-size: 15px; font-family: Arial; color: rgb(17, 85, 204); text-decoration: underline; vertical-align: baseline; white-space: pre-wrap;">http://www.woodlandsprep.org/</span></a><span style="font-size: 15px; font-family: Arial; vertical-align: baseline; white-space: pre-wrap;"> )</span></span></p>
		<p dir="ltr" style="line-height:1.15;margin-top:20pt;margin-bottom:0pt;">
			<span id="docs-internal-guid-0bc2142d-bc9b-1e64-a071-c15c014c9fe2"><span style="font-size: 15px; font-family: Arial; font-weight: bold; vertical-align: baseline; white-space: pre-wrap;">Educaci&oacute;n superior</span></span></p>
		<p dir="ltr" style="line-height:1.15;margin-top:20pt;margin-bottom:0pt;">
			<span id="docs-internal-guid-0bc2142d-bc9b-1e64-a071-c15c014c9fe2"><span style="font-size: 15px; font-family: Arial; vertical-align: baseline; white-space: pre-wrap;">Lone Star College - Montgomery ( </span><a href="http://www.lonestar.edu/montgomery" style="text-decoration:none;"><span style="font-size: 15px; font-family: Arial; color: rgb(17, 85, 204); text-decoration: underline; vertical-align: baseline; white-space: pre-wrap;">http://www.lonestar.edu/montgomery</span></a><span style="font-size: 15px; font-family: Arial; vertical-align: baseline; white-space: pre-wrap;"> )</span></span></p>
		<p dir="ltr" style="line-height:1.15;margin-top:20pt;margin-bottom:0pt;">
			<span id="docs-internal-guid-0bc2142d-bc9b-1e64-a071-c15c014c9fe2"><span style="font-size: 15px; font-family: Arial; vertical-align: baseline; white-space: pre-wrap;">Lone Star-University Center en The Woodlands ( </span><a href="http://www.lonestar.edu/uc-montgomery/" style="text-decoration:none;"><span style="font-size: 15px; font-family: Arial; color: rgb(17, 85, 204); text-decoration: underline; vertical-align: baseline; white-space: pre-wrap;">http://www.lonestar.edu/uc-montgomery/</span></a><span style="font-size: 15px; font-family: Arial; vertical-align: baseline; white-space: pre-wrap;"> )</span></span></p>
		<p dir="ltr" style="line-height:1.15;margin-top:20pt;margin-bottom:0pt;">
			<span id="docs-internal-guid-0bc2142d-bc9b-1e64-a071-c15c014c9fe2"><span style="font-size: 15px; font-family: Arial; vertical-align: baseline; white-space: pre-wrap;">Sam Houston State University - El Centro Woodlands ( </span><a href="http://www.shsu.edu/woodlands/" style="text-decoration:none;"><span style="font-size: 15px; font-family: Arial; color: rgb(17, 85, 204); text-decoration: underline; vertical-align: baseline; white-space: pre-wrap;">http://www.shsu.edu/woodlands/</span></a><span style="font-size: 15px; font-family: Arial; vertical-align: baseline; white-space: pre-wrap;"> )</span></span></p>
		<p dir="ltr" style="line-height:1.15;margin-top:20pt;margin-bottom:0pt;">
			<span id="docs-internal-guid-0bc2142d-bc9b-1e64-a071-c15c014c9fe2"><span style="font-size: 15px; font-family: Arial; vertical-align: baseline; white-space: pre-wrap;">Facultad de Teolog&iacute;a de la Gracia - The Woodlands ( </span><a href="http://www.gsot.edu/" style="text-decoration:none;"><span style="font-size: 15px; font-family: Arial; color: rgb(17, 85, 204); text-decoration: underline; vertical-align: baseline; white-space: pre-wrap;">http://www.gsot.edu/</span></a><span style="font-size: 15px; font-family: Arial; vertical-align: baseline; white-space: pre-wrap;"> )</span></span></p>
		<p dir="ltr" style="line-height:1.15;margin-top:20pt;margin-bottom:0pt;">
			&nbsp;</p>
		<p dir="ltr" style="line-height:1.15;margin-top:20pt;margin-bottom:0pt;">
			<span id="docs-internal-guid-0bc2142d-bc9b-1e64-a071-c15c014c9fe2"><span style="font-size: 15px; font-family: Arial; font-weight: bold; text-decoration: underline; vertical-align: baseline; white-space: pre-wrap;">Actividades Informaci&oacute;n</span></span></p>
		<p dir="ltr" style="line-height:1.15;margin-top:20pt;margin-bottom:0pt;">
			<span id="docs-internal-guid-0bc2142d-bc9b-1e64-a071-c15c014c9fe2"><span style="font-size: 15px; font-family: Arial; font-weight: bold; vertical-align: baseline; white-space: pre-wrap;">Compras</span></span></p>
		<p dir="ltr" style="line-height:1.15;margin-top:20pt;margin-bottom:0pt;">
			<span id="docs-internal-guid-0bc2142d-bc9b-1e64-a071-c15c014c9fe2"><span style="font-size: 15px; font-family: Arial; vertical-align: baseline; white-space: pre-wrap;">The Woodlands Mall ( </span><a href="http://www.thewoodlandsmall.com/" style="text-decoration:none;"><span style="font-size: 15px; font-family: Arial; color: rgb(17, 85, 204); text-decoration: underline; vertical-align: baseline; white-space: pre-wrap;">http://www.thewoodlandsmall.com/</span></a><span style="font-size: 15px; font-family: Arial; vertical-align: baseline; white-space: pre-wrap;"> )</span></span></p>
		<p dir="ltr" style="line-height:1.15;margin-top:20pt;margin-bottom:0pt;">
			<span id="docs-internal-guid-0bc2142d-bc9b-1e64-a071-c15c014c9fe2"><span style="font-size: 15px; font-family: Arial; vertical-align: baseline; white-space: pre-wrap;">Market Street ( </span><a href="http://www.marketstreet-thewoodlands.com/default" style="text-decoration:none;"><span style="font-size: 15px; font-family: Arial; color: rgb(17, 85, 204); text-decoration: underline; vertical-align: baseline; white-space: pre-wrap;">http://www.marketstreet-thewoodlands.com/default</span></a><span style="font-size: 15px; font-family: Arial; vertical-align: baseline; white-space: pre-wrap;"> )</span></span></p>
		<p dir="ltr" style="line-height:1.15;margin-top:20pt;margin-bottom:0pt;">
			<span id="docs-internal-guid-0bc2142d-bc9b-1e64-a071-c15c014c9fe2"><span style="font-size: 15px; font-family: Arial; vertical-align: baseline; white-space: pre-wrap;">The Galleria Mall ( </span><a href="http://www.simon.com/mall/the-galleria" style="text-decoration:none;"><span style="font-size: 15px; font-family: Arial; color: rgb(17, 85, 204); text-decoration: underline; vertical-align: baseline; white-space: pre-wrap;">http://www.simon.com/mall/the-galleria</span></a><span style="font-size: 15px; font-family: Arial; vertical-align: baseline; white-space: pre-wrap;"> )</span></span></p>
		<p dir="ltr" style="line-height:1.15;margin-top:20pt;margin-bottom:0pt;">
			<span id="docs-internal-guid-0bc2142d-bc9b-1e64-a071-c15c014c9fe2"><span style="font-size: 15px; font-family: Arial; font-weight: bold; vertical-align: baseline; white-space: pre-wrap;">Dinning</span></span></p>
		<p dir="ltr" style="line-height:1.15;margin-top:20pt;margin-bottom:0pt;">
			<span id="docs-internal-guid-0bc2142d-bc9b-1e64-a071-c15c014c9fe2"><span style="font-size: 15px; font-family: Arial; vertical-align: baseline; white-space: pre-wrap;">Dinning en la primavera ( </span><a href="http://www.thewoodlands.com/living/waystoplay/dining.html" style="text-decoration:none;"><span style="font-size: 15px; font-family: Arial; color: rgb(17, 85, 204); text-decoration: underline; vertical-align: baseline; white-space: pre-wrap;">http://www.thewoodlands.com/living/waystoplay/dining.html</span></a><span style="font-size: 15px; font-family: Arial; vertical-align: baseline; white-space: pre-wrap;"> )</span></span></p>
		<p dir="ltr" style="line-height:1.15;margin-top:20pt;margin-bottom:0pt;">
			<span id="docs-internal-guid-0bc2142d-bc9b-1e64-a071-c15c014c9fe2"><span style="font-size: 15px; font-family: Arial; font-weight: bold; vertical-align: baseline; white-space: pre-wrap;">Entretenimiento</span></span></p>
		<p dir="ltr" style="line-height:1.15;margin-top:20pt;margin-bottom:0pt;">
			<span id="docs-internal-guid-0bc2142d-bc9b-1e64-a071-c15c014c9fe2"><span style="font-size: 15px; font-family: Arial; vertical-align: baseline; white-space: pre-wrap;">El Cynthia Woods Mitchell Pavilion ( </span><a href="http://www.woodlandscenter.org/" style="text-decoration:none;"><span style="font-size: 15px; font-family: Arial; color: rgb(17, 85, 204); text-decoration: underline; vertical-align: baseline; white-space: pre-wrap;">http://www.woodlandscenter.org/</span></a><span style="font-size: 15px; font-family: Arial; vertical-align: baseline; white-space: pre-wrap;"> )</span></span></p>
		<p dir="ltr" style="line-height:1.15;margin-top:20pt;margin-bottom:0pt;">
			<span id="docs-internal-guid-0bc2142d-bc9b-1e64-a071-c15c014c9fe2"><span style="font-size: 15px; font-family: Arial; vertical-align: baseline; white-space: pre-wrap;">Cinemark en The Woodlands ( </span><a href="http://www.cinemark.com/" style="text-decoration:none;"><span style="font-size: 15px; font-family: Arial; color: rgb(17, 85, 204); text-decoration: underline; vertical-align: baseline; white-space: pre-wrap;">http://www.cinemark.com/</span></a><span style="font-size: 15px; font-family: Arial; vertical-align: baseline; white-space: pre-wrap;"> )</span></span></p>
		<p dir="ltr" style="line-height:1.15;margin-top:20pt;margin-bottom:0pt;">
			<span id="docs-internal-guid-0bc2142d-bc9b-1e64-a071-c15c014c9fe2"><span style="font-size: 15px; font-family: Arial; vertical-align: baseline; white-space: pre-wrap;">Cinemark en Market Street ( </span><a href="http://www.cinemark.com/" style="text-decoration:none;"><span style="font-size: 15px; font-family: Arial; color: rgb(17, 85, 204); text-decoration: underline; vertical-align: baseline; white-space: pre-wrap;">http://www.cinemark.com/</span></a><span style="font-size: 15px; font-family: Arial; vertical-align: baseline; white-space: pre-wrap;"> )</span></span></p>
		<p dir="ltr" style="line-height:1.15;margin-top:20pt;margin-bottom:0pt;">
			<span id="docs-internal-guid-0bc2142d-bc9b-1e64-a071-c15c014c9fe2"><span style="font-size: 15px; font-family: Arial; vertical-align: baseline; white-space: pre-wrap;">Al aire libre Conciertos y espect&aacute;culos ( </span><a href="http://www.thewoodlandstownship-tx.gov/index.aspx?nid=418" style="text-decoration:none;"><span style="font-size: 15px; font-family: Arial; color: rgb(17, 85, 204); text-decoration: underline; vertical-align: baseline; white-space: pre-wrap;">http://www.thewoodlandstownship-tx.gov/index.aspx?nid=418</span></a><span style="font-size: 15px; font-family: Arial; vertical-align: baseline; white-space: pre-wrap;"> )</span></span></p>
		<p dir="ltr" style="line-height:1.15;margin-top:20pt;margin-bottom:0pt;">
			<span id="docs-internal-guid-0bc2142d-bc9b-1e64-a071-c15c014c9fe2"><span style="font-size: 15px; font-family: Arial; vertical-align: baseline; white-space: pre-wrap;">El Country Club Woodlands ( </span><a href="http://www.thewoodlandscc.com/" style="text-decoration:none;"><span style="font-size: 15px; font-family: Arial; color: rgb(17, 85, 204); text-decoration: underline; vertical-align: baseline; white-space: pre-wrap;">http://www.thewoodlandscc.com/</span></a><span style="font-size: 15px; font-family: Arial; vertical-align: baseline; white-space: pre-wrap;"> )</span></span></p>
		<p dir="ltr" style="line-height:1.15;margin-top:20pt;margin-bottom:0pt;">
			<span id="docs-internal-guid-0bc2142d-bc9b-1e64-a071-c15c014c9fe2"><span style="font-size: 15px; font-family: Arial; vertical-align: baseline; white-space: pre-wrap;">El Club en Carlton Woods ( </span><a href="http://www.carltonwoods.com/" style="text-decoration:none;"><span style="font-size: 15px; font-family: Arial; color: rgb(17, 85, 204); text-decoration: underline; vertical-align: baseline; white-space: pre-wrap;">http://www.carltonwoods.com/</span></a><span style="font-size: 15px; font-family: Arial; vertical-align: baseline; white-space: pre-wrap;"> )</span></span></p>
		<p dir="ltr" style="line-height:1.15;margin-top:20pt;margin-bottom:0pt;">
			<span id="docs-internal-guid-0bc2142d-bc9b-1e64-a071-c15c014c9fe2"><span style="font-size: 15px; font-family: Arial; vertical-align: baseline; white-space: pre-wrap;">Canongate en The Woodlands ( </span><a href="http://www.canongategolf.com/" style="text-decoration:none;"><span style="font-size: 15px; font-family: Arial; color: rgb(17, 85, 204); text-decoration: underline; vertical-align: baseline; white-space: pre-wrap;">http://www.canongategolf.com/</span></a><span style="font-size: 15px; font-family: Arial; vertical-align: baseline; white-space: pre-wrap;"> )</span></span></p>
		<p dir="ltr" style="line-height:1.15;margin-top:20pt;margin-bottom:0pt;">
			<span id="docs-internal-guid-0bc2142d-bc9b-1e64-a071-c15c014c9fe2"><span style="font-size: 15px; font-family: Arial; vertical-align: baseline; white-space: pre-wrap;">Centros de Recreacion ( </span><a href="http://www.thewoodlands.com/living/waystoplay/recreation.html" style="text-decoration:none;"><span style="font-size: 15px; font-family: Arial; color: rgb(17, 85, 204); text-decoration: underline; vertical-align: baseline; white-space: pre-wrap;">http://www.thewoodlands.com/living/waystoplay/recreation.html</span></a><span style="font-size: 15px; font-family: Arial; vertical-align: baseline; white-space: pre-wrap;"> )</span></span></p>
		<p dir="ltr" style="line-height:1.15;margin-top:20pt;margin-bottom:0pt;">
			<span id="docs-internal-guid-0bc2142d-bc9b-1e64-a071-c15c014c9fe2"><span style="font-size: 15px; font-family: Arial; vertical-align: baseline; white-space: pre-wrap;">Deportes ( </span><a href="http://www.thewoodlands.com/living/waystoplay/sports.html" style="text-decoration:none;"><span style="font-size: 15px; font-family: Arial; color: rgb(17, 85, 204); text-decoration: underline; vertical-align: baseline; white-space: pre-wrap;">http://www.thewoodlands.com/living/waystoplay/sports.html</span></a><span style="font-size: 15px; font-family: Arial; vertical-align: baseline; white-space: pre-wrap;"> )</span></span></p>
		<p dir="ltr" style="line-height:1.15;margin-top:20pt;margin-bottom:0pt;">
			<span id="docs-internal-guid-0bc2142d-bc9b-1e64-a071-c15c014c9fe2"><span style="font-size: 15px; font-family: Arial; font-weight: bold; vertical-align: baseline; white-space: pre-wrap;">Organizaciones de artes esc&eacute;nicas</span></span></p>
		<p dir="ltr" style="line-height:1.15;margin-top:20pt;margin-bottom:0pt;">
			<span id="docs-internal-guid-0bc2142d-bc9b-1e64-a071-c15c014c9fe2"><span style="font-size: 15px; font-family: Arial; vertical-align: baseline; white-space: pre-wrap;">La Banda de Concierto Woodlands ( </span><a href="http://www.woodlandsband.org/" style="text-decoration:none;"><span style="font-size: 15px; font-family: Arial; color: rgb(17, 85, 204); text-decoration: underline; vertical-align: baseline; white-space: pre-wrap;">http://www.woodlandsband.org/</span></a><span style="font-size: 15px; font-family: Arial; vertical-align: baseline; white-space: pre-wrap;"> )</span></span></p>
		<p dir="ltr" style="line-height:1.15;margin-top:20pt;margin-bottom:0pt;">
			<span id="docs-internal-guid-0bc2142d-bc9b-1e64-a071-c15c014c9fe2"><span style="font-size: 15px; font-family: Arial; vertical-align: baseline; white-space: pre-wrap;">El Ballet Woodlands C&iacute;vica ( </span><a href="http://www.woodlandscivicballet.org/" style="text-decoration:none;"><span style="font-size: 15px; font-family: Arial; color: rgb(17, 85, 204); text-decoration: underline; vertical-align: baseline; white-space: pre-wrap;">http://www.woodlandscivicballet.org/</span></a><span style="font-size: 15px; font-family: Arial; vertical-align: baseline; white-space: pre-wrap;"> )</span></span></p>
		<p dir="ltr" style="line-height:1.15;margin-top:20pt;margin-bottom:0pt;">
			<span id="docs-internal-guid-0bc2142d-bc9b-1e64-a071-c15c014c9fe2"><span style="font-size: 15px; font-family: Arial; vertical-align: baseline; white-space: pre-wrap;">Class Act Productions ( </span><a href="http://www.classactproductions.org/" style="text-decoration:none;"><span style="font-size: 15px; font-family: Arial; color: rgb(17, 85, 204); text-decoration: underline; vertical-align: baseline; white-space: pre-wrap;">http://www.classactproductions.org/</span></a><span style="font-size: 15px; font-family: Arial; vertical-align: baseline; white-space: pre-wrap;"> )</span></span></p>
		<p dir="ltr" style="line-height:1.15;margin-top:20pt;margin-bottom:0pt;">
			<span id="docs-internal-guid-0bc2142d-bc9b-1e64-a071-c15c014c9fe2"><span style="font-size: 15px; font-family: Arial; font-weight: bold; vertical-align: baseline; white-space: pre-wrap;">Congregaciones Religiosas</span></span></p>
		<p dir="ltr" style="line-height:1.15;margin-top:20pt;margin-bottom:0pt;">
			<span id="docs-internal-guid-0bc2142d-bc9b-1e64-a071-c15c014c9fe2"><span style="font-size: 15px; font-family: Arial; vertical-align: baseline; white-space: pre-wrap;">Lugares de Culto de Primavera (http://www.thewoodlands.net/leps/letitem.cfm?LetID=48)</span></span></p>
		<p dir="ltr" style="line-height:1.15;margin-top:20pt;margin-bottom:0pt;">
			<span id="docs-internal-guid-0bc2142d-bc9b-1e64-a071-c15c014c9fe2"><span style="font-size: 15px; font-family: Arial; font-weight: bold; vertical-align: baseline; white-space: pre-wrap;">Hospitalidad</span></span></p>
		<p dir="ltr" style="line-height:1.15;margin-top:20pt;margin-bottom:0pt;">
			<span id="docs-internal-guid-0bc2142d-bc9b-1e64-a071-c15c014c9fe2"><span style="font-size: 15px; font-family: Arial; vertical-align: baseline; white-space: pre-wrap;">The Woodlands Resort &amp; Conference Center ( </span><a href="http://www.woodlandsresort.com/" style="text-decoration:none;"><span style="font-size: 15px; font-family: Arial; color: rgb(17, 85, 204); text-decoration: underline; vertical-align: baseline; white-space: pre-wrap;">http://www.woodlandsresort.com/</span></a><span style="font-size: 15px; font-family: Arial; vertical-align: baseline; white-space: pre-wrap;"> )</span></span></p>
		<p dir="ltr" style="line-height:1.15;margin-top:20pt;margin-bottom:0pt;">
			<span id="docs-internal-guid-0bc2142d-bc9b-1e64-a071-c15c014c9fe2"><span style="font-size: 15px; font-family: Arial; vertical-align: baseline; white-space: pre-wrap;">The Woodlands Hidrov&iacute;a Marriott Hotel &amp; Convention Center ( </span><a href="http://www.marriott.com/hotels/travel/houmw-the-woodlands-waterway-marriott-hotel-and-convention-center/" style="text-decoration:none;"><span style="font-size: 15px; font-family: Arial; color: rgb(17, 85, 204); text-decoration: underline; vertical-align: baseline; white-space: pre-wrap;">http://www.marriott.com/hotels/travel/houmw-the-woodlands-waterway-marriott-hotel-and-convention-center/</span></a><span style="font-size: 15px; font-family: Arial; vertical-align: baseline; white-space: pre-wrap;"> )</span></span></p>
		<p dir="ltr" style="line-height:1.15;margin-top:20pt;margin-bottom:0pt;">
			<span id="docs-internal-guid-0bc2142d-bc9b-1e64-a071-c15c014c9fe2"><span style="font-size: 15px; font-family: Arial; vertical-align: baseline; white-space: pre-wrap;">Hyatt Market Street, The Woodlands ( </span><a href="http://marketstreetthewoodlands.hyatt.com/en/hotel/home.html" style="text-decoration:none;"><span style="font-size: 15px; font-family: Arial; color: rgb(17, 85, 204); text-decoration: underline; vertical-align: baseline; white-space: pre-wrap;">http://marketstreetthewoodlands.hyatt.com/en/hotel/home.html</span></a><span style="font-size: 15px; font-family: Arial; vertical-align: baseline; white-space: pre-wrap;"> )</span></span></p>
		<p dir="ltr" style="line-height:1.15;margin-top:20pt;margin-bottom:0pt;">
			&nbsp;</p>
		<p dir="ltr" style="line-height:1.15;margin-top:20pt;margin-bottom:0pt;">
			<span id="docs-internal-guid-0bc2142d-bc9b-1e64-a071-c15c014c9fe2"><span style="font-size: 15px; font-family: Arial; font-weight: bold; text-decoration: underline; vertical-align: baseline; white-space: pre-wrap;">Informaci&oacute;n para la Salud</span></span></p>
		<p dir="ltr" style="line-height:1.15;margin-top:20pt;margin-bottom:0pt;">
			<span id="docs-internal-guid-0bc2142d-bc9b-1e64-a071-c15c014c9fe2"><span style="font-size: 15px; font-family: Arial; vertical-align: baseline; white-space: pre-wrap;">Memorial Hermann Hospital Woodlands ( </span><a href="http://www.memorialhermann.org/" style="text-decoration:none;"><span style="font-size: 15px; font-family: Arial; color: rgb(17, 85, 204); text-decoration: underline; vertical-align: baseline; white-space: pre-wrap;">http://www.memorialhermann.org/</span></a><span style="font-size: 15px; font-family: Arial; vertical-align: baseline; white-space: pre-wrap;"> )</span></span></p>
		<p dir="ltr" style="line-height:1.15;margin-top:20pt;margin-bottom:0pt;">
			<span id="docs-internal-guid-0bc2142d-bc9b-1e64-a071-c15c014c9fe2"><span style="font-size: 15px; font-family: Arial; vertical-align: baseline; white-space: pre-wrap;">Memorial Hermann Prevenci&oacute;n y Centro de Recuperaci&oacute;n - The Woodlands ( </span><a href="http://parc.memorialhermann.org/" style="text-decoration:none;"><span style="font-size: 15px; font-family: Arial; color: rgb(17, 85, 204); text-decoration: underline; vertical-align: baseline; white-space: pre-wrap;">http://parc.memorialhermann.org/</span></a><span style="font-size: 15px; font-family: Arial; vertical-align: baseline; white-space: pre-wrap;"> )</span></span></p>
		<p dir="ltr" style="line-height:1.15;margin-top:20pt;margin-bottom:0pt;">
			<span id="docs-internal-guid-0bc2142d-bc9b-1e64-a071-c15c014c9fe2"><span style="font-size: 15px; font-family: Arial; vertical-align: baseline; white-space: pre-wrap;">El Hospital Woodlands de San Lucas ( </span><a href="http://www.stlukeswoodlands.com/" style="text-decoration:none;"><span style="font-size: 15px; font-family: Arial; color: rgb(17, 85, 204); text-decoration: underline; vertical-align: baseline; white-space: pre-wrap;">http://www.stlukeswoodlands.com/</span></a><span style="font-size: 15px; font-family: Arial; vertical-align: baseline; white-space: pre-wrap;"> )</span></span></p>
		<p dir="ltr" style="line-height:1.15;margin-top:20pt;margin-bottom:0pt;">
			<span id="docs-internal-guid-0bc2142d-bc9b-1e64-a071-c15c014c9fe2"><span style="font-size: 15px; font-family: Arial; vertical-align: baseline; white-space: pre-wrap;">Lakeside Hospital de San Lucas ( </span><a href="http://www.stlukeslakeside.com/" style="text-decoration:none;"><span style="font-size: 15px; font-family: Arial; color: rgb(17, 85, 204); text-decoration: underline; vertical-align: baseline; white-space: pre-wrap;">http://www.stlukeslakeside.com/</span></a><span style="font-size: 15px; font-family: Arial; vertical-align: baseline; white-space: pre-wrap;"> )</span></span></p>
		<p dir="ltr" style="line-height:1.15;margin-top:20pt;margin-bottom:0pt;">
			<span id="docs-internal-guid-0bc2142d-bc9b-1e64-a071-c15c014c9fe2"><span style="font-size: 15px; font-family: Arial; vertical-align: baseline; white-space: pre-wrap;">MD Anderson de Atenci&oacute;n Regional Center en The Woodlands ( </span><a href="http://www.mdanderson.org/patient-and-cancer-information/care-centers-and-clinics/regional-care/the-woodlands/index.html?cmpid=RCC_Woodlands_Vanity" style="text-decoration:none;"><span style="font-size: 15px; font-family: Arial; color: rgb(17, 85, 204); text-decoration: underline; vertical-align: baseline; white-space: pre-wrap;">http://www.mdanderson.org/patient-and-cancer-information/care-centers-and-clinics/regional-care/the-woodlands/index.html?cmpid=RCC_Woodlands_Vanity</span></a><span style="font-size: 15px; font-family: Arial; vertical-align: baseline; white-space: pre-wrap;"> )</span></span></p>
		<div>
			&nbsp;</div>
					</div>	
				</div>	
			</div>
		</div>
	</div>
</div>
<script src="js/popup.js"></script>